[package]
name = "fake_data_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["rt"] }
rand = "0.8.5"
surrealdb = "2.0.4"
serde_json = "1.0.132"
serde = "1.0.214"
chrono = "0.4.38"
mockd = { version = "=0.4.34", features = ["all"] }
